### PR TITLE
Use focused helper

### PR DESCRIPTION
**Pull request by linc01n**

### CODE REVIEW

**Comment by jasonm23** [comment]
needs more description @linc01n

**Comment by jasonm23** [comment]
Never mind, I thought this was an issue.  Merging.

**Comment by jasonm23** [comment]
Merged! Thank you 👍

**Comment by linc01n** [comment]
You defined `focused` in L103

`focused = -> Window.focused()`

**Comment by linc01n** [comment]
https://github.com/linc01n/Phoenix-config/blame/67ee792fe5eb4864bcd96cee58828b2e0d805fc8/phoenix.js.litcoffee#L103

**Pull request merged**
